on:
  email:
    imap:
      host: imap.zoho.in
      user: ${{secrets.EMAIL_USER}}
      password: ${{secrets.EMAIL_PASSWORD}}
jobs:
  print:
    name: Notify Email-Subject to Telegram
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          subject: ${{on.email.outputs.subject}}
          attachmentsEmail: ${{on.email.outputs.attachments[0]}}
          from_email: ${{on.email.outputs.from}}
          outputs_email: ${{on.email.outputs}}
        run: |
          echo subject: $subject
          echo attachmentEmails: $attachmentsEmail
          echo from_email: $from_email
          echo outputs_email: $outputs_email

#       - name: Update apt and install youtube-dl and ffmpeg
#       - run: sudo apt update
#       - run: sudo apt install ffmpeg
#       - run: sudo apt install youtube-dl
      
#       - name: extract audio from youtube channel drums
#       - run: youtube-dl -o 'out.%(ext)s' -x https://www.youtube.com/watch?v=xk3BvNLeNgw
#       - run: youtube-dl -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4' https://www.youtube.com/watch?v=3AyMjyHu1bA  ## extract mp4 and m4a
#       youtube-dl --postprocessor-args "-ss 0:0:00 -to 0:1:30" -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4' https://www.youtube.com/watch?v=3AyMjyHu1bA

      
      - name: Send telegram email message to telegram
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          document:  ${{(on.email.outputs.attachments[0].content)}}
          message: |
                   You've got a Email
                   ${{(on.email.outputs.subject)}} and 
                   ${{(on.email.outputs.text)}} and
                   ${{(on.email.outputs)}}
                   ${{(on.email.outputs.attachments[0].filename)}}
      # - uses: actions/checkout@v2
      # - uses: FedericoCarboni/setup-ffmpeg@v1
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      # - run: ffmpeg -i input.mp4 -vn -acodec libmp3lame -ab 128k -ar 44100 -ac 2 output.mp3
      # - run: youtube-dl -o  https://www.youtube.com/watch?v=xk3BvNLeNgw 
      # - uses: actions/setup-python@v2
      #   with:
      #     python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
      # - name: download
      #   run: |
      #     git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
      #     git pull --rebase
      #     chmod +x ./bin/youtube-dl
      #     ./bin/youtube-dl --config-location config.txt
      #     tar -czvf downloads.tar.gz downloads/*.m4a
      - name: Send mail via zohomail
        uses: dawidd6/action-send-mail@v3
        with:
          # Required mail server address:
          server_address: smtp.zoho.in
          # Required mail server port:
          server_port: 465
          # Optional (recommended): mail server username:
          username:  ${{secrets.EMAIL_USER}}
          # Optional (recommended) mail server password:
          password: ${{secrets.EMAIL_PASSWORD}}
          # Required mail subject:
          subject: Re ${{(on.email.outputs.subject)}}
          # Required recipients' addresses:
          to:  ${{(on.email.outputs.from.value[0].address)}}
          # Required sender full name (address can be skipped):
          from: ${{ secrets.FROM_EMAIL_ID }}
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional plain body:
          body: |
                We have received your email. This is Shiva Auto Robo
                ${{(on.email.outputs.text)}}
          # Optional recipient of the email response:
          reply_to: ${{ secrets.FROM_EMAIL_ID }}
          # Optional unsigned/invalid certificates allowance:
          ignore_cert: true
          # Optional converting Markdown to HTML (set content_type to text/html too):
          convert_markdown: true
          # Optional attachments:
          attachments: ${{(on.email.outputs.attachments[0].content)}}
